"""create normalized_sales table

Revision ID: 0f13d0315602
Revises: 929b146fe2d4
Create Date: 2026-06-24 23:24:18.659514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f13d0315602'
down_revision: Union[str, None] = '929b146fe2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('normalized_sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False, comment='pos | website | uber_eats | doordash | other'),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('raw_row', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploaded_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_sales_category'), 'normalized_sales', ['category'], unique=False)
    op.create_index(op.f('ix_normalized_sales_channel'), 'normalized_sales', ['channel'], unique=False)
    op.create_index(op.f('ix_normalized_sales_sale_date'), 'normalized_sales', ['sale_date'], unique=False)
    op.create_index(op.f('ix_normalized_sales_sku'), 'normalized_sales', ['sku'], unique=False)
    op.create_index(op.f('ix_normalized_sales_store_id'), 'normalized_sales', ['store_id'], unique=False)
    op.create_index(op.f('ix_normalized_sales_upload_id'), 'normalized_sales', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_normalized_sales_upload_id'), table_name='normalized_sales')
    op.drop_index(op.f('ix_normalized_sales_store_id'), table_name='normalized_sales')
    op.drop_index(op.f('ix_normalized_sales_sku'), table_name='normalized_sales')
    op.drop_index(op.f('ix_normalized_sales_sale_date'), table_name='normalized_sales')
    op.drop_index(op.f('ix_normalized_sales_channel'), table_name='normalized_sales')
    op.drop_index(op.f('ix_normalized_sales_category'), table_name='normalized_sales')
    op.drop_table('normalized_sales')
    # ### end Alembic commands ###
