"""add ai_strategy_reports table

Revision ID: 4a5ead59118f
Revises: 0f13d0315602
Create Date: 2026-06-28 00:14:54.580300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5ead59118f'
down_revision: Union[str, None] = '0f13d0315602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_strategy_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('products_analyzed', sa.JSON(), nullable=False, comment='The slow-moving products data sent to the AI'),
    sa.Column('strategy_title', sa.String(length=500), nullable=False),
    sa.Column('products_to_promote', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('target_customer_segment', sa.Text(), nullable=False),
    sa.Column('recommended_offer', sa.Text(), nullable=False),
    sa.Column('sms_copy', sa.Text(), nullable=False),
    sa.Column('email_subject', sa.String(length=500), nullable=False),
    sa.Column('email_body', sa.Text(), nullable=False),
    sa.Column('social_caption', sa.Text(), nullable=False),
    sa.Column('expected_impact', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_strategy_reports_store_id'), 'ai_strategy_reports', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_strategy_reports_store_id'), table_name='ai_strategy_reports')
    op.drop_table('ai_strategy_reports')
    # ### end Alembic commands ###
