"""multi-store support and transfer ledger

Revision ID: f3d82c1a9b47
Revises: a91c4f7b3e58
Create Date: 2026-07-20

Phase 14:
  - users.role ('owner'/'staff', existing rows become 'owner')
  - users.store_id (staff pinned to one store)
  - stores.owner_id UNIQUE constraint DROPPED (one owner, many stores)
  - transfers / transfer_items / settlement_payments tables
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d82c1a9b47'
down_revision: Union[str, None] = 'a91c4f7b3e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── users: role + staff store assignment ─────────────────────────────────
    op.add_column('users', sa.Column(
        'role', sa.String(length=20), nullable=False, server_default='owner'))
    op.add_column('users', sa.Column(
        'store_id', sa.UUID(), nullable=True,
        comment='Staff only: the store this account is pinned to'))
    op.create_foreign_key(
        'fk_users_store_id', 'users', 'stores', ['store_id'], ['id'],
        ondelete='CASCADE')

    # ── stores: allow many stores per owner ──────────────────────────────────
    # The one-store-per-owner rule was enforced by a UNIQUE INDEX (created by
    # the original autogenerated migration), not a named constraint.
    # Replace it with a plain (non-unique) index.
    op.drop_index(op.f('ix_stores_owner_id'), table_name='stores')
    op.create_index(op.f('ix_stores_owner_id'), 'stores', ['owner_id'], unique=False)

    # ── transfers ────────────────────────────────────────────────────────────
    op.create_table('transfers',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('from_store_id', sa.UUID(), nullable=False),
        sa.Column('to_store_id', sa.UUID(), nullable=False),
        sa.Column('transfer_date', sa.Date(), nullable=False),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('created_by_user_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['from_store_id'], ['stores.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['to_store_id'], ['stores.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_transfers_from_store_id'), 'transfers', ['from_store_id'])
    op.create_index(op.f('ix_transfers_to_store_id'), 'transfers', ['to_store_id'])
    op.create_index(op.f('ix_transfers_transfer_date'), 'transfers', ['transfer_date'])

    # ── transfer_items ───────────────────────────────────────────────────────
    op.create_table('transfer_items',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('transfer_id', sa.UUID(), nullable=False),
        sa.Column('product_name', sa.String(length=500), nullable=False),
        sa.Column('sku', sa.String(length=100), nullable=True),
        sa.Column('quantity', sa.Numeric(12, 3), nullable=False),
        sa.Column('unit_cost', sa.Numeric(12, 2), nullable=False,
                  comment='WHOLESALE cost per unit — transfers settle at cost between stores'),
        sa.Column('line_total', sa.Numeric(12, 2), nullable=False),
        sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_transfer_items_transfer_id'), 'transfer_items', ['transfer_id'])

    # ── settlement_payments ──────────────────────────────────────────────────
    op.create_table('settlement_payments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('payer_store_id', sa.UUID(), nullable=False),
        sa.Column('payee_store_id', sa.UUID(), nullable=False),
        sa.Column('amount', sa.Numeric(12, 2), nullable=False),
        sa.Column('paid_on', sa.Date(), nullable=False),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('created_by_user_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['payer_store_id'], ['stores.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['payee_store_id'], ['stores.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_settlement_payments_payer_store_id'), 'settlement_payments', ['payer_store_id'])
    op.create_index(op.f('ix_settlement_payments_payee_store_id'), 'settlement_payments', ['payee_store_id'])


def downgrade() -> None:
    op.drop_table('settlement_payments')
    op.drop_table('transfer_items')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_stores_owner_id'), table_name='stores')
    op.create_index(op.f('ix_stores_owner_id'), 'stores', ['owner_id'], unique=True)
    op.drop_constraint('fk_users_store_id', 'users', type_='foreignkey')
    op.drop_column('users', 'store_id')
    op.drop_column('users', 'role')
